# Generated by Django 4.2.4 on 2023-11-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('fechaIncorporacion', models.DateField()),
                ('añoNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.TextField(blank=True)),
            ],
        ),
    ]
